"""initial: models table

Revision ID: f68255d89392
Revises: 
Create Date: 2026-05-04 09:47:43.171582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68255d89392'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('backbone', sa.Enum('B0', 'B2', 'B3', name='backbone'), nullable=False),
    sa.Column('training_completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_sheets', sa.Integer(), nullable=False),
    sa.Column('training_pixels', sa.Integer(), nullable=False),
    sa.Column('miou_overall', sa.Float(), nullable=False),
    sa.Column('miou_rice_paddy', sa.Float(), nullable=False),
    sa.Column('miou_dry_field', sa.Float(), nullable=False),
    sa.Column('miou_orchard', sa.Float(), nullable=False),
    sa.Column('miou_greenhouse', sa.Float(), nullable=False),
    sa.Column('deployment_state', sa.Enum('PRODUCTION', 'STAGING', 'ARCHIVED', name='deployment_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_backbone'), 'models', ['backbone'], unique=False)
    op.create_index(op.f('ix_models_deployment_state'), 'models', ['deployment_state'], unique=False)
    op.create_index(op.f('ix_models_training_completed_at'), 'models', ['training_completed_at'], unique=False)
    op.create_index(op.f('ix_models_version'), 'models', ['version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_models_version'), table_name='models')
    op.drop_index(op.f('ix_models_training_completed_at'), table_name='models')
    op.drop_index(op.f('ix_models_deployment_state'), table_name='models')
    op.drop_index(op.f('ix_models_backbone'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
